### ISSUE TITLE
Guidemo v 0.0.10 | The setting feature is not work

### ISSUE THREAD

**Issue by Icramss** [ohmae/GuiDemo#1]
# Expected behavior

Expected the Setting feature is work and function

# Actual behavior

Clicking on Setting does not function

# How to reproduce

- Download app on
- Open the app
- click on 3 dots on the right side of the top
- Click Settings
- it does not work

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version :0.0.10

# Recording of the bug

https://youtu.be/Ecs8IEHkp9k

**Comment by ohmae** [comment]
Fixed. https://github.com/ohmae/GuiDemo/commit/24abc022aacf89b191ac772bb7dd85fd14dd6b90
Supplement: There are pop-up menus that will not happen in on other screens. It aims to display a popup. What does not happen is correct behavior.
